---
bases:
  - "../../environments/{{ .Environment.Name }}/config.yaml"

---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: amphizzapp
    chart: ../../../amphizzchart/
    namespace: default
    version: 0.0.1
  - name: amphizzdb
    chart: bitnami/mariadb
    namespace: default
    version: 9.3.14
    values:
      - db.yaml.gotmpl