helmfiles:
  - "releases/promstack/helmfile.yaml"
  - "releases/ingress-nginx/helmfile.yaml"
  - "releases/cert-manager/helmfile.yaml"
  - "releases/cert-manager-letsencrypt/helmfile.yaml"
  #- "releases/oauth2-proxy/helmfile.yaml"
environments:
  amphiesta:

helmDefaults:
  atomic: true
  cleanupOnFail: false
  wait: true
  timeout: 60
  tillerless: true
  verify: false

missingFileHandler: Error
