
name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          check-latest: true
      - name: Maven Package
        env: # Or as an environment variable
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: mvn -B spring-boot:build-image -Dimage.tag=${GITHUB_REF##*/}
